### PR TITLE
Delay saving of the id during VM creation + Hike up wait timeout

### LINKED ISSUE #21: Terraform destroys incompleted SL virtual guest if re-run 'terraform apply' after Timeout error
If creating a new virtual guest takes more than 10 minutes then terraform exits with timeout error and SoftLayer continues creating server. When re-run 'terraform apply' then after refreshing the state it starts destroying that instance and creates a new one afterwards. 
## Steps to reproduce
- Create softlayer_virtual_guest resource with reference to private image.
- Run 'terraform apply' and wait 10 minutes to get Timeout Error
  `softlayer_virtual_guest.data-node: Error waiting for virtual machine (24773585) to become ready: timeout while waiting for state to become 'idle' (last state: 'active', timeout: 10m0s)`
- Re-run 'terraform apply' and check output
## Expected result

Terraform shouldn't initiate destroying instance but should wait for completion instead.
## Actual result

Terraform initiates destroying of the incompletely created virtual guest and then creating a new one
### softlayer.tf

```
data "softlayer_image_template" "private_redhat" {
    name = "Private virtual RedHat 6.7 2016-6-22"
}

resource "softlayer_virtual_guest" "data-node" {
    name = "${var.dn_name}"
    domain = "${var.dn_domain}"
    datacenter = "${var.dn_region}"
    hourly_billing = "${var.dn_hourly_billing}"
    private_network_only = "${var.dn_private_network_only}"
    network_speed = "${var.dn_public_network_speed}"
    cpu = "${var.dn_cpu}"
    ram = "${var.dn_ram}"
    local_disk = "${var.dn_local_disk}"

    front_end_vlan {
       id = "${var.dn_frontend_vlan_id}"
    }
    back_end_vlan {
       id = "${var.dn_backend_vlan_id}"
    }

    image_id = "${data.softlayer_image_template.private_redhat.id}"
}
```
### Output

```
me> terraform apply
data.softlayer_image_template.private_redhat: Refreshing state...
softlayer_virtual_guest.data-node: Creating...
softlayer_virtual_guest.data-node: Still creating... (10s elapsed)
...
softlayer_virtual_guest.data-node: Still creating... (10m0s elapsed)
Error applying plan:

1 error(s) occurred:

* softlayer_virtual_guest.data-node: Error waiting for virtual machine (24773585) to become ready: timeout while waiting for state to become 'idle' (last state: 'active', timeout: 10m0s)

me> terraform apply
data.softlayer_image_template.private_redhat: Refreshing state...
softlayer_virtual_guest.data-node: Destroying...
softlayer_virtual_guest.data-node: Still destroying... (10s elapsed)
...
softlayer_virtual_guest.data-node: Destruction complete
softlayer_virtual_guest.data-node: Creating...
softlayer_virtual_guest.data-node: Still creating... (6s elapsed)
softlayer_virtual_guest.console: Still creating... (10m6s elapsed)
Error applying plan:

1 error(s) occurred:

* softlayer_virtual_guest.data-node: Error waiting for virtual machine (24773585) to become ready: timeout while waiting for state to become 'idle' (last state: 'active', timeout: 10m0s)
```

### PR DESCRIPTION
**Pull request by renier**
Resolves #21

@bondyk Please review and see if this works for you.

### CODE REVIEW

**Comment by Freyert** [comment]
Maybe it would be helpful to set these timeouts as global constants? I believe it would make maintenance quite a bit more simple to have all of these constant values in one place, with well labeled variable names.

**Comment by bondyk** [comment]
My preferred approach is to have these values configurable for softlayer provider (together with username and api_key).
The second part of the problem (destroying after timeout failure) in my opinion should be fixed by resuming to actual state of the virtual guest by showing "Still creating..." message. Current fix will eliminate destroying of these servers but they won't be managed by terraform any more.

**Comment by riethm** [comment]
See my comment in #21

**Comment by renier** [comment]
@bondyk, First, can you try the branch and let me know how it works for you? Do you still get a timeout?

Second, making the wait times configurable is something we have to think more about. There is a separate issue that you opened for that already. This PR is not addressing that on purpose.

Third, this PR does address the destruction of the resource after a timeout failure. However, it is not possible to simply resume from a broken state on `terraform apply`. That is beyond the plugin's capability, and looks like something that could be presented to the Terraform community itself. Having said that, after a timeout you could use `terraform import` instead of `terraform refresh` to import an existing resource into your state file, to get it managed by terraform.

**Comment by renier** [comment]
@bondyk It seems this problem would go away entirely if you use the correct properties when specifying the vlans. Let me know.

**Comment by bondyk** [comment]
@renier The problem with destroying disappeared after removing ids from vlan settings. Increasing timeout fixes the problem as well but I can change it locally as temporary solution. However I prefer to have it configurable for provider (as I mentioned before :))

**Comment by renier** [comment]
@bondyk I'll reopen the PR then and just increase the timeout.

**Pull request merged**
