### PR TITLE
#177 remove id from resource schema

### PR DESCRIPTION
**Pull request by c4po**

### CODE REVIEW

**Comment by renier** [comment]
A couple of issues with this:

1. We don't know which users are relying on this old behavior, so changing this may break them.
2. If we still decide to make this change to keep current with the latest terraform core, we should rename the id to something else (e.g. `domainId` for the domain resource) and update the documentation so as not to lose that information that might be needed by users (and would allow them to migrate to this new version more easily).

Thoughts?

**Comment by c4po** [comment]
without make any change, this plugin won't work with new version of terraform. which force softlayer user to stay with old version of terraform. and we cannot get acc test pass.
once this changes merged in, we can bump up the release number so old version terraform user still can find the right version work for them,

I don't fell terraform user have access to the resource Id directly. If terraform can manage it though the plugin interface, why should we maintain another copy?

**Comment by renier** [comment]
@c4po Yes, something should be done, however the SoftLayer Ids remain a problem. It is something that can certainly be accessed today. Seems to me we would just rename the Ids and update the docs.

**Comment by renier** [comment]
#177

**Comment by c4po** [comment]
Hi @renier , can you merge this PR and make a new release?

**Pull request merged**
